/**
 * Created By Nguyen Cong Thanh on 03/04/2019 15:28.
 *
 * Copyright Intelin 2019.
 */

export default {
  COUNTER_TYPE_INCREMENT: 'COUNTER_TYPE_INCREMENT',
  COUNTER_TYPE_DECREMENT: 'COUNTER_TYPE_DECREMENT',
  USER_TYPE_GET_ALL: 'USER_TYPE_GET_ALL',
  USER_TYPE_GET_ALL_SUCCESS: 'USER_TYPE_GET_ALL_SUCESS',
  USER_TYPE_CREATE: 'USER_TYPE_CREATE',
  USER_TYPE_CREATE_SUCCESS: 'USER_TYPE_CREATE_SUCCESS'
}
